services:
  - type: web
    name: sunic-newbiz-ai
    runtime: python
    plan: free
    region: singapore          
    branch: main

    buildCommand: pip install -r requirements.txt

    startCommand: >
      streamlit run main.py
      --server.port $PORT
      --server.address 0.0.0.0
      --server.headless true
      --browser.gatherUsageStats false

    healthCheckPath: /_stcore/health

    envVars:
      - key: PYTHON_VERSION
        value: "3.11"

      - key: HF_HOME
        value: /opt/render/project/.cache/huggingface

      - key: OPENAI_API_KEY
        sync: false

      - key: OPENAI_MODEL
        sync: false
      - key: F5_OPENAI_MODEL
        sync: false
